export {
  MESSAGE_EMAIL_THROTTLE_MS,
  MINIMAL_MESSAGE_EMAIL,
  NOTIFICATION_CATEGORIES,
  NOTIFICATION_CATEGORY_COPY,
  absoluteUrl,
  buildNotificationEmail,
  categoryForKind,
  channelEnabled,
  defaultPreference,
  isNotificationCategory,
  isSafeAppPath,
  messageEmailDecision,
  notificationPath,
  resolvePreference,
  resolveSecret,
  resolveUnsubscribeSecret,
  signUnsubscribeToken,
  usesMinimalEmail,
  verifyUnsubscribeToken,
  winningEmailClaim,
} from "../../../supabase/functions/_shared/notificationPolicy";

export type {
  EmailClaim,
  MessageEmailDecision,
  NotificationAudience,
  NotificationCategory,
  NotificationChannel,
  NotificationEmail,
  PreferenceFlags,
  UnsubscribeToken,
} from "../../../supabase/functions/_shared/notificationPolicy";
