-- Owner helper: approve an existing contractor so matching can include them.
-- Prefer Admin → Approvals in the website (admin_approve_contractor RPC).
-- This SQL remains a dashboard fallback. Never invent demo contractors.
-- Replace the email, then run in the SQL editor. There is no self-approve.
-- Paying a signup fee does not approve anyone.

-- UPDATE public.profiles
-- SET account_status = 'ACTIVE'
-- WHERE email = 'CONTRACTOR@example.com'
--   AND account_type = 'CONTRACTOR';
--
-- UPDATE public.contractor_profiles cp
-- SET
--   approval_status = 'APPROVED',
--   approved_at = now(),
--   onboarding_status = 'COMPLETE'
-- FROM public.profiles p
-- WHERE cp.profile_id = p.id
--   AND p.email = 'CONTRACTOR@example.com';
