const STATE_NAMES: Record<string, string> = {
  al: "AL",
  alabama: "AL",
  ak: "AK",
  alaska: "AK",
  az: "AZ",
  arizona: "AZ",
  ar: "AR",
  arkansas: "AR",
  ca: "CA",
  california: "CA",
  co: "CO",
  colorado: "CO",
  ct: "CT",
  connecticut: "CT",
  de: "DE",
  delaware: "DE",
  dc: "DC",
  districtofcolumbia: "DC",
  fl: "FL",
  florida: "FL",
  ga: "GA",
  georgia: "GA",
  hi: "HI",
  hawaii: "HI",
  id: "ID",
  idaho: "ID",
  il: "IL",
  illinois: "IL",
  in: "IN",
  indiana: "IN",
  ia: "IA",
  iowa: "IA",
  ks: "KS",
  kansas: "KS",
  ky: "KY",
  kentucky: "KY",
  la: "LA",
  louisiana: "LA",
  me: "ME",
  maine: "ME",
  md: "MD",
  maryland: "MD",
  ma: "MA",
  massachusetts: "MA",
  mi: "MI",
  michigan: "MI",
  mn: "MN",
  minnesota: "MN",
  ms: "MS",
  mississippi: "MS",
  mo: "MO",
  missouri: "MO",
  mt: "MT",
  montana: "MT",
  ne: "NE",
  nebraska: "NE",
  nv: "NV",
  nevada: "NV",
  nh: "NH",
  newhampshire: "NH",
  nj: "NJ",
  newjersey: "NJ",
  nm: "NM",
  newmexico: "NM",
  ny: "NY",
  newyork: "NY",
  nc: "NC",
  northcarolina: "NC",
  nd: "ND",
  northdakota: "ND",
  oh: "OH",
  ohio: "OH",
  ok: "OK",
  oklahoma: "OK",
  or: "OR",
  oregon: "OR",
  pa: "PA",
  pennsylvania: "PA",
  ri: "RI",
  rhodeisland: "RI",
  sc: "SC",
  southcarolina: "SC",
  sd: "SD",
  southdakota: "SD",
  tn: "TN",
  tennessee: "TN",
  tx: "TX",
  texas: "TX",
  ut: "UT",
  utah: "UT",
  vt: "VT",
  vermont: "VT",
  va: "VA",
  virginia: "VA",
  wa: "WA",
  washington: "WA",
  wv: "WV",
  westvirginia: "WV",
  wi: "WI",
  wisconsin: "WI",
  wy: "WY",
  wyoming: "WY",
};

export function normalizeCity(value: string | null | undefined): string {
  return (value ?? "")
    .replace(/\s+,/g, ",")
    .replace(/,+/g, ",")
    .replace(/\s+/g, " ")
    .replace(/,\s*$/g, "")
    .trim();
}

export function normalizeState(value: string | null | undefined): string {
  const raw = (value ?? "").trim().replace(/\./g, "");
  if (!raw) return "";
  const key = raw.toLowerCase().replace(/[^a-z]/g, "");
  return STATE_NAMES[key] ?? raw.toUpperCase();
}

export function formatCityStateZip(
  city: string | null | undefined,
  state: string | null | undefined,
  zip?: string | null,
): string {
  const place = [normalizeCity(city), normalizeState(state)].filter(Boolean).join(", ");
  return [place, (zip ?? "").trim()].filter(Boolean).join(" ");
}
