const now = "2026-04-02T15:00:00.000Z";

export const project = {
  id: "proj-1",
  customer_id: "user-layout",
  category_id: "cat-fence",
  title: "Replace a leaning cedar fence before the storm",
  description:
    "The side fence is leaning toward the neighbor's driveway. About 40 feet, some posts are rotten. Please include haul-away.",
  status: "ESTIMATES_AVAILABLE",
  completeness: "HIGH",
  city: "Atlanta",
  state: "GA",
  zip_code: "30318",
  timing: "WITHIN_A_WEEK",
  preferred_date: null,
  budget_min_cents: 80000,
  budget_max_cents: 180000,
  draft_step: 8,
  selected_contractor_profile_id: null,
  selected_estimate_id: null,
  selected_booking_id: null,
  posted_at: now,
  selected_at: null,
  scope_revision: 1,
  accepting_connections: true,
  reference_number: 1042,
  created_at: now,
  updated_at: now,
};

export const booking = {
  id: "book-1",
  project_id: "proj-1",
  estimate_id: "est-1",
  customer_id: "user-layout",
  contractor_profile_id: "pro-1",
  status: "IN_PROGRESS",
  amount_cents: 145000,
  approved_delta_cents: 0,
  billable_amount_cents: 145000,
  is_repeat: false,
  fee_kind: "ORIGINAL",
  fee_schedule_id: null,
  fee_schedule_version: null,
  fee_brackets_snapshot: null,
  min_fee_cents_snapshot: null,
  max_fee_cents_snapshot: null,
  fee_cents: 0,
  contractor_earnings_cents: 145000,
  customer_amount_cents: 145000,
  fee_locked: false,
  fee_locked_at: null,
  payments_live: false,
  charges_live: false,
  expires_at: null,
  confirmed_at: now,
  started_at: now,
  completed_at: null,
  cancelled_at: null,
  disputed_at: null,
  cancel_reason: null,
  customer_hired_at: now,
  contractor_hired_at: now,
  created_at: now,
  updated_at: now,
};

export const estimate = {
  id: "est-1",
  project_id: "proj-1",
  opportunity_id: "opp-1",
  contractor_profile_id: "pro-1",
  status: "VIEWED",
  total_cents: 145000,
  notes: "Includes posts, pickets, and haul-away. Gate hardware is extra if the old hinges are seized.",
  duration_hours: 12,
  available_from: "2026-04-10",
  valid_until: "2026-04-30",
  submitted_at: now,
  first_viewed_at: now,
  last_viewed_at: now,
  view_count: 1,
  created_at: now,
};

export const estimateItems = [
  {
    id: "item-1",
    estimate_id: "est-1",
    kind: "LABOR",
    label: "Remove and reset leaning cedar fence along the side yard",
    quantity: 12,
    unit_label: "hours",
    unit_cents: 8500,
    line_total_cents: 102000,
    sort_order: 0,
  },
  {
    id: "item-2",
    estimate_id: "est-1",
    kind: "MATERIALS",
    label: "Posts, pickets, and concrete",
    quantity: 1,
    unit_label: "lot",
    unit_cents: 43000,
    line_total_cents: 43000,
    sort_order: 1,
  },
];

export const contractorPublic = {
  id: "pro-1",
  display_label: "Northside Fence Co.",
  primary_trade: "Fence repair",
  categories: ["Fence repair"],
  service_area: "Atlanta, within 25 miles of 30318",
  years_experience: 11,
  rating_average: 4.8,
  rating_count: 6,
  badges: [],
  short_description: "Independent fence crew. Local, not a national lead mill.",
  about: "We repair and replace wood fences for homeowners around northwest Atlanta.",
};

export const categories = [
  {
    id: "cat-fence",
    slug: "fence-repair",
    name: "Fence repair",
    blurb: "Posts, pickets, and gates.",
    sort_order: 1,
    is_active: true,
    is_regulated: false,
    requires_verified_credential: false,
  },
  {
    id: "cat-handyman",
    slug: "handyman",
    name: "Handyman",
    blurb: "Small repairs around the house.",
    sort_order: 2,
    is_active: true,
    is_regulated: false,
    requires_verified_credential: false,
  },
];

export const questions = [
  {
    id: "q-1",
    category_id: "cat-fence",
    prompt: "About how long is the fence?",
    help_text: "A rough length is enough.",
    kind: "SINGLE_CHOICE",
    options: ["Under 20 feet", "20 to 50 feet", "Longer than 50 feet"],
    is_required: true,
    sort_order: 1,
    is_active: true,
  },
];

const opportunityProject = {
  ...project,
  status: "POSTED",
};

export const opportunity = {
  id: "opp-1",
  project_id: "proj-1",
  contractor_profile_id: "pro-1",
  match_id: null,
  status: "AVAILABLE",
  available_at: now,
  responded_at: null,
  expires_at: null,
  created_at: now,
  projects: opportunityProject,
};

export const contractorProfile = {
  id: "pro-1",
  profile_id: "user-layout",
  business_name: "Northside Fence Co.",
  headline: "Wood fences, gates, and storm repairs",
  bio: "Independent local crew. We do not share a phone number on the public card.",
  years_experience: 11,
  accepting_work: true,
  min_job_cents: 15000,
  max_job_cents: 500000,
  onboarding_status: "COMPLETE",
  approval_status: "APPROVED",
  website_url: "https://example.com/northside-fence-company-very-long-url",
  primary_trade: "Fence repair",
  license_number: null,
  insurance_carrier: null,
};

export const thread = {
  thread_id: "thread-1",
  project_id: "proj-1",
  contractor_profile_id: "pro-1",
  project_title: project.title,
  city: "Atlanta",
  state: "GA",
  contractor_label: "Northside Fence Co.",
  other_party_label: "Christopher",
  last_message_at: now,
  last_preview: "I can look Thursday morning if the side yard is clear.",
  last_sender_is_viewer: false,
  unread_count: 1,
  last_read_at: null,
  booking_id: "book-1",
  opportunity_id: "opp-1",
};

export const messages = [
  {
    id: "msg-1",
    thread_id: "thread-1",
    sender_profile_id: "pro-1",
    body: "I can look Thursday morning if the side yard is clear. See https://example.com/fence-prep-notes-for-homeowners-with-a-very-long-path",
    created_at: now,
  },
];

export const sharedContact = {
  eligible: true,
  customer_shared: true,
  name: "Christopher Homeowner",
  phone: "404-555-0199",
  email: "christopher.longname.homeowner@prioritypropertypros.example",
  street_line1: "1842 Very Long Street Name Avenue Northwest",
  street_line2: null,
  city: "Atlanta",
  state: "GA",
  zip_code: "30318",
};

export const approval = {
  contractor_profile_id: "pro-1",
  profile_id: "user-layout",
  business_name: "Northside Fence Co.",
  contact_name: "Pat Lee",
  first_name: "Pat",
  last_name: "Lee",
  email: "pat.lee.contractor.applications@prioritypropertypros.example",
  phone: "404-555-0144",
  categories: [{ id: "cat-fence", name: "Fence repair", slug: "fence-repair" }],
  service_area: "25 miles from 30318",
  service_areas: [
    {
      id: "area-1",
      mode: "RADIUS",
      center_zip: "30318",
      radius_miles: 25,
      zip_codes: ["30318", "30327"],
      label: "Northwest Atlanta",
    },
  ],
  applied_at: now,
  account_status: "ACTIVE",
  approval_status: "PENDING",
  onboarding_status: "COMPLETE",
  headline: "Wood fences",
  bio: "Local fence repair.",
  primary_trade: "Fence repair",
  years_experience: 11,
  license_number: null,
  insurance_carrier: null,
  website_url: null,
  accepting_work: true,
  min_job_cents: 15000,
  max_job_cents: 500000,
  approved_at: null,
  approved_by: null,
  rejected_at: null,
  rejected_by: null,
  rejection_reason: null,
  info_requested_at: null,
  info_requested_by: null,
  info_request_message: null,
  identity_review_required: false,
  identity_review_at: null,
  identity_review_fields: [],
  credentials: [],
};
